Interests Page Mock-up
DevDatesDevelopers/Front-End-Mockup pull request #20
Opened 2023-03-15 10:58 UTC by Stili559

Interests Page Mock-up с дизайна от Figma + js file с работещи бутони. Тоест при активиране на бутон дизайна му се сменя и при деактивиране той се връща в нормалният си вид + “continue” бутона е деактивиран и при избиране на точно 5 интереса той се активира.

2023-03-15 11:00 UTC, Stili559 commented
Closes #9

2023-03-15 11:14 UTC, Kardam-Simeonov requested changes
Освен промените в кода, трябва да добавиш Interests.vue като router-link в App.vue и след това да го добавиш в router/index.js, като не забравиш да импортнеш view-то. Виж как са го направили с HomeView.vue ако имаш въпроси.

2023-03-15 11:14 UTC, Kardam-Simeonov commented on front-end-mockup/src/components/Interests.vue
> +</head>
```suggestion
```

2023-03-15 11:14 UTC, Kardam-Simeonov commented on front-end-mockup/src/components/Interests.vue
> +<body>
```suggestion
<div>
```

2023-03-15 11:14 UTC, Kardam-Simeonov commented on front-end-mockup/src/components/Interests.vue
> +</html>
```suggestion
</div>
```

2023-03-15 11:14 UTC, Kardam-Simeonov commented on front-end-mockup/src/components/Interests.vue
> +
```suggestion
```

2023-03-16 07:58 UTC, Kardam-Simeonov requested changes

2023-03-16 07:58 UTC, Kardam-Simeonov commented on front-end-mockup/src/views/InterestsView.vue
> +<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css"/>
```suggestion
```

2023-03-16 07:58 UTC, Kardam-Simeonov commented on front-end-mockup/src/views/InterestsView.vue
> +  }
Това е МАСИВЕН BLOAT. В никакъв случай, дали статични бутони или fetchнати от сървър не трявбва да се прави CSS selector за всеки елемент. Отделно position: absolute е пълна безумица. Един бутон трявбва да има един и същ template, като се подреждат с flexbox автоматично.
```suggestion
```

2023-03-16 07:58 UTC, Kardam-Simeonov commented on front-end-mockup/src/views/InterestsView.vue
> +    <span v-if="index === 17"><i class="fa-solid fa-school"></i> </span>
Това не се прави така. В проекта има компонент [Icon от Iconify](https://docs.iconify.design/icon-components/vue/), който се възползва от [масивна библиотека от безплатни икони](https://icones.js.org/). Когато интересите се взимат от сървър, той трябва да предоставя името на иконата, което се bindva към icon атрибута на компонента.

2023-03-16 07:58 UTC, Kardam-Simeonov commented on front-end-mockup/src/views/InterestsView.vue
> +      <button :id="'button'+(index+1)" @click="interactsButtons('button'+(index+1))" :toggle="false" :class="{'Photography-Button': index === 0, 'Streaming-Button': index === 1,  'Cooking-Button': in
Това ще се замени с един template за бутон, който трябва да се стилизира с [tailwindcss](https://tailwindcss.com/docs/installation)

2023-03-16 07:58 UTC, Kardam-Simeonov commented on front-end-mockup/src/views/InterestsView.vue
> +};
Този метод трябва само да променя bool стойността за дали бутона на определен индекс е селектиран. Използвайки [conditional class binding](https://stackoverflow.com/questions/43210508/vue-js-conditional-class-style-binding), интересите и полето с текста, който предупреждава за твърде много селектирани елементи трябва да си сменят изгледа в зависимост от стойностите, който гледат. Във Vue не се използва DOM манипулация, защото е много вероятно да се счупи, поради Single Page Application модела.

2023-03-20 11:24 UTC, Kardam-Simeonov requested changes
Виж suggestion-а

2023-03-20 11:24 UTC, Kardam-Simeonov commented on front-end-mockup/src/views/InterestsView.vue
> +    </button>
```suggestion
      <button @click="interactsButtons(index)" :toggle="false" class="Design-Button"
        :class="{ 'Selected': buttonBr[index] === 1 }">
        <Icon :icon="button.icon" class="Design-Icon" /> {{ button.name }}
      </button>
```

2023-03-20 11:24 UTC, Kardam-Simeonov commented on front-end-mockup/src/views/InterestsView.vue
> +      <a ref="selectButton" class="Selection">Please select only five interests</a>
```suggestion
    <button ref="submitButton" class="Continue-Button" :class="{ 'Selected': totalSelected === 5 }"
      :disabled="totalSelected === 5">Submit</button>
    <a ref="selectButton" class="Selection">{{ submitButtonCaption }}</a>
```

2023-03-20 11:24 UTC, Kardam-Simeonov commented on front-end-mockup/src/views/InterestsView.vue
> +      "Tennis", "Swimming", "Traveling", "Music", "Videogames", "Programming", "Student"]
```suggestion
      buttons: [
        {
          name: "Photography",
          icon: "mdi-light:camera"
        },
        {
          name: "Streaming",
          icon: "mdi-light:monitor"
        },
        {
          name: "Cooking",
          icon: "ph:bowl-food"
        },
        {
          name: "Running",
          icon: "ph:person-simple-run"
        },
        {
          name: "Painting",
          icon: "ph:paint-brush"
        },
        {
          name: "Football",
          icon: "ph:soccer-ball"
        },
        {
          name: "Drink",
          icon: "arcticons:drinkable"
        },
        {
          name: "Writing",
          icon: "ph:pen"
        },
        {
          name: "Reading",
          icon: "ph:book"
        },
        {
          name: "Shopping",
          icon: "ph:shopping-cart"
        },
        {
          name: "Skiing",
          icon: "ph:snowflake"
        },
        {
          name: "Tennis",
          icon: "ph:tennis-ball"
        },
        {
          name: "Swimming",
          icon: "ph:swimming-pool"
        },
        {
          name: "Traveling",
          icon: "ph:airplane"
        },
        {
          name: "Music",
          icon: "ph:music-notes"
        },
        {
          name: "Videogames",
          icon: "ph:game-controller"
        },
        {
          name: "Programming",
          icon: "carbon:cics-program"
        },
        {
          name: "Student",
          icon: "ph:student"
        }
      ],
      totalSelected: 0,
      submitButtonCaption: "Please select only five interests"
```

2023-03-20 11:24 UTC, Kardam-Simeonov commented on front-end-mockup/src/views/InterestsView.vue
> +    },
```suggestion
    interactsButtons(index) {
      if (this.buttonBr[index] === 0) {
        this.buttonBr[index] = 1;
        this.totalSelected++;
      } else {
        this.buttonBr[index] = 0;
        this.totalSelected--;
      }

      if (this.totalSelected === 5) {
        this.submitButtonCaption = "";
      }
      else {
        this.submitButtonCaption = "Please select only five interests";
      }
    }
```

2023-03-20 11:46 UTC, Kardam-Simeonov approved these changes

2023-03-20 11:46 UTC, merged